print("######        #####")
print("#     #      # ")
print("#     #      #")
print("#     #      #")
print("#     #      #")
print("######       #")
print("#             #####")
print("##     ROSHAN      #")
print("# #   SHIVNANI     #")
print("#  #               #")
print("#   #              #")
print("#    #        #####")
